# Generated by Django 5.2.10 on 2026-01-27 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the dataset was uploaded')),
                ('file', models.FileField(help_text='The uploaded CSV file', upload_to='datasets/')),
                ('total_equipment', models.IntegerField(default=0, help_text='Total number of equipment entries')),
                ('avg_flowrate', models.FloatField(default=0.0, help_text='Average flowrate across all equipment')),
                ('avg_pressure', models.FloatField(default=0.0, help_text='Average pressure across all equipment')),
                ('avg_temperature', models.FloatField(default=0.0, help_text='Average temperature across all equipment')),
                ('equipment_types', models.TextField(default='{}', help_text='JSON string containing equipment type distribution')),
                ('user', models.ForeignKey(help_text='The user who uploaded this dataset', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(help_text='Name of the equipment', max_length=200)),
                ('equipment_type', models.CharField(help_text='Type/category of equipment', max_length=100)),
                ('flowrate', models.FloatField(help_text='Flowrate value')),
                ('pressure', models.FloatField(help_text='Pressure value')),
                ('temperature', models.FloatField(help_text='Temperature value')),
                ('dataset', models.ForeignKey(help_text='The dataset this equipment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='equipment.dataset')),
            ],
            options={
                'verbose_name': 'Equipment Data',
                'verbose_name_plural': 'Equipment Data',
                'ordering': ['equipment_name'],
            },
        ),
    ]
